### DEV values for RabbitMQ Helm chart.
rabbitmq:
  username: user
  password: your_secure_password # BITTE ÄNDERN SIE DIESES PASSWORT IN DER PRODUKTION!
### DEV values for PostgreSQL Helm chart.
postgresql:
  username: user
  password: password
  database: mydb
  image: postgres:16
  port: 5432
