# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rabbitmq-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rabbitmq-chart.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1 # Fest auf 1 gesetzt, da keine HA gewünscht ist
  selector:
    matchLabels:
      {{- include "rabbitmq-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rabbitmq-chart.selectorLabels" . | nindent 8 }}
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: amqp
              containerPort: {{ .Values.service.amqpPort }}
            - name: management
              containerPort: {{ .Values.service.managementPort }}
          envFrom:
            - secretRef:
                name: {{ include "rabbitmq-chart.fullname" . }}-credentials
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: rabbitmq-persistent-storage
              mountPath: /var/lib/rabbitmq
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: rabbitmq-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "rabbitmq-chart.fullname" . }}-data
      {{- end }}
