apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgresql-chart.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postgresql-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgresql-chart.name" . }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: {{ .Values.postgresql.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql-chart.fullname" . }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql-chart.fullname" . }}
                  key: password
