apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-chart.fullname" . }}
type: Opaque
data:
  username: {{ .Values.postgresql.username | b64enc | quote }}
  password: {{ .Values.postgresql.password | b64enc | quote }}
